<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>

<body>
    <h1>手写Promise</h1>
    <script>
        // Promise/A+规范特征
        // 1.有3种状态pending, fulfilled, rejected，有两种状态变更pending => fulfilled 和 pending => rejected
        // 2.new Promise实例化接受一个参数，这个参数是个函数，这个函数是立即执行的
        // 3.这个函数中有两个参数，分别是resovle和reject，用来变更Promise的状态
        // 4.有then方法，接受两个参数，一个是成功的回调，一个是失败的回调
        // 5.Promise有一个value保存成功的值，在调用.then的时候如果成功，执行onFulFilled函数，返回value值。还有一个reason值，保存失败原因，在执行onRejected的时候返回
        // 6.then方法返回一个新的Promise实例，实现.then的的链式调用。且每个then方法参数都有默认值,已达到值穿透效果
        (() => {
            const PENDING = 'PENDING'
            const FULFILLED = 'FULFILLED'
            const REJECTED = 'REJECTED'

            class Promise {
                constructor(exectuor) {
                    // 存放成功状态的值，默认为 undefined
                    this.value = null
                    // 存放失败状态的值，默认为 undefined
                    this.reason = null
                    // 默认状态为 PENDING
                    this.status = PENDING

                    // 成功回调
                    this.onFulFilledFunctions = []
                    // 失败回调
                    this.onRejectedFunctions = []

                    // 改变Promise的状态为FULFILLED，并把成功的值保存到value
                    const resolve = (value) => {
                        // 避免执行两次
                        if (this.status === PENDING) {
                            this.status = FULFILLED
                            this.value = value
                            for (let fn of this.onFulFilledFunctions) {
                                fn()
                            }
                        }
                    }

                    // 改变Promise状态为REJECTED，并把失败原因保存到reason
                    const reject = (reason) => {
                        // 避免执行两次
                        if (this.status === PENDING) {
                            this.status = REJECTED
                            this.reason = reason
                            for (let fn of this.onRejectedFunctions) {
                                fn()
                            }
                        }
                    }

                    try {
                        // 立即执行，将 resolve 和 reject 函数传给使用者  
                        exectuor.call(this, resolve, reject)
                    } catch (error) {
                        // 发生异常时执行失败逻辑
                        reject(error)
                    }
                }

                then(onFulFilled, onRejected) {
                    // 设置回到函数的默认值，达到值穿透效果
                    onFulFilled = typeof onFulFilled === 'function' ? onFulFilled : v => v
                    onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err }

                    // 这里是简版，实际情况需要考虑回到函数本身是否为Promise的情况，以及是否多次调用等
                    const promise2 = new Promise((resolve, reject) => {
                        if (this.status === FULFILLED) {
                            try {
                                resolve(onFulFilled(this.value))
                            } catch (error) {
                                reject(error)
                            }
                        }

                        if (this.status === REJECTED) {
                            try {
                                resolve(onRejected(this.reason))
                            } catch (error) {
                                reject(error)
                            }
                        }

                        if (this.status === PENDING) {
                            this.onFulFilledFunctions.push(() => {
                                try {
                                    resolve(onFulFilled(this.value))
                                } catch (error) {
                                    reject(error)
                                }
                            })
                            this.onRejectedFunctions.push(() => {
                                try {
                                    resolve(onRejected(this.reason))
                                } catch (error) {
                                    reject(error)
                                }
                            })
                        }
                    })
                    return promise2
                }
            }

            const p1 = new Promise((resolve, reject) => {
                console.log('resolve before')
                setTimeout(() => {
                    resolve('resovle p1')
                    // reject('rejecte p1')
                }, 2000)
                // resolve('resovle p1')
                console.log('resolve after')
            }).then(value => value + 222).then().then(console.log, console.log)

            console.log(p1)
        })()
    </script>

</body>

</html>